### ISSUE TITLE
Automatic text and jumping cursor

### ISSUE THREAD

**Issue by CodingFan72** [tmaegel/ntodotxt#27]
Hi!  

When I create a new task and start entering the description of the task, the app writes the creation date again directly in front of the text.  

E.g. '2024-02-21 2024-02-21Task'.  

When I delete the "second" date and want to change the description, the cursor suddenly jumps to the end of the line while I am typing. 

This makes it almost impossible to enter a task.

I use a Samsung S23 with Android Android 14.

**Comment by tmaegel** [comment]
This happends because there is a missing whitespace between "2024-02-21" and "Task". The todo.txt format splits all information by whitespace.

But I see a general problem here. The way it is already implemented is error-prone and prone to confusion. So I will change it so that only the actual description and tags are entered in the text field and the rest via the fields below.

**Comment by CodingFan72** [comment]
Hi Toni,

thanks for your reply.

Ok, if I can get a blank space then it works. 😉

But I had to figure out how it works first:
When I place the cursor behind the creation date (that has already been entered automatically) and enter a space, then the cursor jumps back directly behind the date (as if I had not entered anything). Only when I enter a space again (and then the task description) it works.

The first video shows the situation when I don't enter the space "twice":

https://github.com/tmaegel/ntodotxt/assets/76176989/f24f85ea-319c-4f58-98fd-4a607e41963b

The second video shows the situation when I enter the space "twice":

https://github.com/tmaegel/ntodotxt/assets/76176989/2743ec14-d234-45f1-9a78-af32ce8fe41e

**Comment by David-Else** [comment]
I am also having the same problem, look forward to a fix :)
