### ISSUE TITLE
Possibility to define a user-defined path of remote todo.txt

### ISSUE THREAD

**Issue by Grydpype** [tmaegel/ntodotxt#56]
I would like to direct the app to (root)/tasks/todo.txt, but it looks like I am entering my Webdav URL incorrectly as I keep getting "Failed to list files in directory / on remote https://magentacloud.de/remote.php/webdav/".

(Oddly enough the user name following the address has a suffixed / (slash) ...)

Any hints/tips where I might be erring?

Cheers,
kai.

**Comment by tmaegel** [comment]
The username is automatically appended to the URL, if not already done.
So the best thing to do is to simply enter "/remote.php/dav/files/" as the base URL.

Or am I misunderstanding your problem?

**Comment by Grydpype** [comment]
Good morning,

thanks for the reply; unfortunately that does not yet solve my problem.

I am trying to connect to DeutscheTelekom's MagentaCloud (which is a Nextcloud-server).

Telekom tells me the standard path is _https://magentacloud.de/remote.php/webdav_, which has so far worked for other android apps accessing or syncing the data; for instance Simpletask. The authentication in ntodotxt appears to work, but the app is unable to retrieve the file list (error **Failed to list files in directory / on remote ...**).

I have also tried using the suggestion in your reply as base URL instead of Telekom's suggestion, also no success.

Any suggestions which variations I could still try?

Kind regards,
kai.

**Comment by tmaegel** [comment]
Okay I think I identified the problem. Your `todo.txt` is not located on the root path, but under `/tasks/todo.txt`.

Unfortunately there is still no real possibility to define a user-defined path of the remote `todo.txt`. So the authentication succeeded, but the app expects a `todo.txt` on the root path.

You can verify my assumption if you move your `todo.txt` to the root path.

**Comment by Grydpype** [comment]
I copied my todo.txt into the root folder, but unfortunately there was no change in the behaviour; it's still **Failed to list files in directory /**

**Comment by tmaegel** [comment]
Okay the only idea I have is that I appending the username automatically if not already done to the base url/path. Perhaps this does only works with standalone nextcloud instances (with which I have tested this). So the resulting base url is always for example `<url>/remote.php/dav/files/<username>`. Perhaps the magentacloud handle this different and doesn't work with a base url contains the username. **I have to make this configurable too.**

Can you verify my assumption with your magentacloud for me by trying to connect to it via an other app (e.g. desktop), but with the following url: `https://magentacloud.de/remote.php/webdav/<username>`.

If it succeeds and you can see your `todo.txt` in your root directory my assumption is wrong otherwise it is right.

**Comment by tmaegel** [comment]
Okay, thanks for testing.

I think I'll make the following things configurable and hope it will help in the future.
* A) Custom path of `todo.txt` on remote side
* B) Don't append the username per default onto the base url
  * Add a hint that in some cases its necessary and in some not

I think I can implement B) very quickly. Maybe in the next few weeks.

**Comment by Grydpype** [comment]
Thanks for your work; since Simpletask is no longer supported, an alternative for Android is very welcome.

I synced my todo.txt with your app using syncthing and I like it; btw I also like the buttons near the top of the screen. But since syncthing is peer2peer, that is not an option for me.

Regards,
kai.

**Comment by Grydpype** [comment]
Short feedback to version 0.10.0:

Logging in to Webdav cloud now works & todo.txt is loaded; very nice.
